# Generated by Django 4.2.20 on 2025-04-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0003_rename_phone_verified_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='phonebook',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='metadata',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_message_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='category',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('transactional', 'Transactional'), ('reminder', 'Reminder'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
